services:
   db:
     image: mongo:7.0.5
     ports:
       - "27017:27017"
       - "9229:9229"
     volumes:
       - mongo-data:/data/db
   nest:
     depends_on:
       - db
       - postgres
       - supertokens
     build: .
     volumes:
       - .:/usr/src/app
#     develop:
#       watch:
#         - action: sync
#           path: ./src
#           target: /usr/src/app/src
#         - action: rebuild
#           path: package.json
#         - action: rebuild
#           path: yarn.lock
     ports:
       - "3000:3000"

   postgres:
     image: 'postgres:16.2'
     environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: postgres
       POSTGRES_DB: supertokens
     ports:
       - "5432:5432"
#     restart: unless-stopped
     volumes:
       - postgres-data:/var/lib/postgresql/data
     healthcheck:
       test: [ 'CMD', 'pg_isready', '-U', 'supertokens_user', '-d', 'supertokens' ]
       interval: 5s
       timeout: 5s
       retries: 5
   supertokens:
     image: registry.supertokens.io/supertokens/supertokens-postgresql:7.0
     depends_on:
       postgres:
         condition: service_healthy
     ports:
       - "3567:3567"
     environment:
       POSTGRESQL_CONNECTION_URI: "postgresql://postgres:postgres@postgres:5432/supertokens"
#     restart: unless-stopped
     healthcheck:
       test: >
         bash -c 'exec 3<>/dev/tcp/127.0.0.1/3567 && echo -e "GET /hello HTTP/1.1\r\nhost: 127.0.0.1:3567\r\nConnection: close\r\n\r\n" >&3 && cat <&3 | grep "Hello"'
       interval: 10s
       timeout: 5s
       retries: 5
volumes:
  mongo-data:
  postgres-data: